# Generated by Django 4.1 on 2022-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(4, 'goalkeeper'), (1, 'forward'), (3, 'defender'), (2, 'midfielder')], default=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.IntegerField(choices=[(6, 'admin'), (5, 'goalkeeper-trainer'), (3, 'physiotherapist'), (1, 'trainer'), (2, 'sub-trainer'), (4, 'doctor')]),
        ),
    ]
