# Generated by Django 4.1 on 2022-11-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_academy_advertiser_club_helps_info_kross_long_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(2, 'midfielder'), (3, 'defender'), (1, 'forward'), (4, 'goalkeeper')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'admin'), (2, 'user')], null=True),
        ),
    ]
