# Generated by Django 4.1 on 2022-11-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_players_position_alter_staff_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='host_goal',
            new_name='host_action',
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.IntegerField(blank=True, choices=[(1, 'yellow-card'), (2, 'red-card')], null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='subs',
            field=models.ManyToManyField(blank=True, null=True, to='main.substitute'),
        ),
        migrations.AlterField(
            model_name='guestaction',
            name='action',
            field=models.IntegerField(blank=True, choices=[(1, 'yellow-card'), (2, 'red-card')], null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(1, 'forward'), (4, 'goalkeeper'), (2, 'midfielder'), (3, 'defender')], default=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.IntegerField(choices=[(2, 'sub-trainer'), (3, 'physiotherapist'), (1, 'trainer'), (6, 'admin'), (5, 'goalkeeper-trainer'), (4, 'doctor')]),
        ),
    ]
