# Generated by Django 4.1 on 2022-11-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_players_position_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='sub_captain',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(3, 'defender'), (1, 'forward'), (2, 'midfielder'), (4, 'goalkeeper')], default=1),
        ),
    ]
