# Generated by Django 4.1 on 2022-11-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_number_alter_players_position_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='helps',
        ),
        migrations.RemoveField(
            model_name='game',
            name='kross',
        ),
        migrations.RemoveField(
            model_name='game',
            name='long_passes',
        ),
        migrations.AddField(
            model_name='passes',
            name='status',
            field=models.IntegerField(choices=[(1, 'passes'), (2, 'crosses'), (3, 'helps'), (4, 'long-passes')], default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='game',
            name='passes',
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(4, 'goalkeeper'), (2, 'midfielder'), (1, 'forward'), (3, 'defender')], default=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.IntegerField(choices=[(3, 'physiotherapist'), (5, 'goalkeeper-trainer'), (1, 'trainer'), (4, 'doctor'), (6, 'admin'), (2, 'sub-trainer')]),
        ),
        migrations.DeleteModel(
            name='Helps',
        ),
        migrations.DeleteModel(
            name='Kross',
        ),
        migrations.DeleteModel(
            name='Long',
        ),
        migrations.AddField(
            model_name='game',
            name='passes',
            field=models.ManyToManyField(to='main.passes'),
        ),
    ]
