# Generated by Django 4.1 on 2022-11-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_players_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(1, 'forward'), (2, 'midfielder'), (3, 'defender'), (4, 'goalkeeper')], default=1),
        ),
    ]
