# Generated by Django 4.1 on 2022-11-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_passes_percent_alter_passes_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passes',
            name='percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(4, 'goalkeeper'), (2, 'midfielder'), (3, 'defender'), (1, 'forward')], default=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.IntegerField(choices=[(2, 'sub-trainer'), (3, 'physiotherapist'), (5, 'goalkeeper-trainer'), (4, 'doctor'), (6, 'admin'), (1, 'trainer')]),
        ),
    ]
