# Generated by Django 4.1 on 2022-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_players_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='sub_captain',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='players',
            name='captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(1, 'forward'), (3, 'defender'), (4, 'goalkeeper'), (2, 'midfielder')], default=1),
        ),
    ]
