# Generated by Django 4.1 on 2022-11-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_passes_percent_alter_players_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(3, 'defender'), (1, 'forward'), (2, 'midfielder'), (4, 'goalkeeper')], default=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.IntegerField(choices=[(4, 'doctor'), (1, 'trainer'), (3, 'main-analytic'), (2, 'sub-trainer'), (6, 'admin'), (5, 'goalkeeper-trainer')]),
        ),
    ]
