# Generated by Django 4.1 on 2022-11-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_players_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='academy/')),
                ('text', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=210)),
                ('logo', models.ImageField(upload_to='fc/')),
                ('players', models.ManyToManyField(to='main.players')),
                ('staff', models.ManyToManyField(to='main.staff')),
            ],
        ),
        migrations.RenameModel(
            old_name='Pass',
            new_name='Passes',
        ),
        migrations.DeleteModel(
            name='Academy',
        ),
        migrations.RemoveField(
            model_name='club',
            name='players',
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(default=1, upload_to='fc/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='name',
            field=models.CharField(default=1, max_length=210),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='trainer',
            field=models.CharField(default=1, max_length=210),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='helps',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.helps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='kross',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.kross'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='long_passes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.long'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='passes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.passes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='passion',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='logo',
            field=models.ImageField(upload_to='advertiser/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='info',
            name='logo',
            field=models.ImageField(upload_to='info/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(choices=[(0, 'no rating'), (1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')], default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videos',
            field=models.FileField(upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='main.fc'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(to='main.productimage'),
        ),
    ]
