# Generated by Django 4.1 on 2022-11-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_about_fc_rename_pass_passes_delete_academy_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='Images',
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(4, 'goalkeeper'), (2, 'midfielder'), (1, 'forward'), (3, 'defender')], default=1),
        ),
    ]
