# Generated by Django 4.1 on 2022-11-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_players_position_squad_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=210)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='province',
        ),
        migrations.RemoveField(
            model_name='order',
            name='town',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=1, max_length=210),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(1, 'forward'), (2, 'midfielder'), (3, 'defender'), (4, 'goalkeeper')], default=1),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL'), (6, '3XL')]),
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_on', to='main.line')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_out', to='main.squad')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.region'),
            preserve_default=False,
        ),
    ]
