# Generated by Django 4.1 on 2022-11-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_players_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(2, 'midfielder'), (4, 'goalkeeper'), (1, 'forward'), (3, 'defender')], default=1),
        ),
    ]
