# Generated by Django 4.1 on 2022-11-09 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_bonus_alter_players_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='game',
            name='host',
        ),
        migrations.AddField(
            model_name='game',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.line'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='subs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.substitute'),
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(3, 'defender'), (2, 'midfielder'), (1, 'forward'), (4, 'goalkeeper')], default=1),
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='main.club')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='main.fc')),
            ],
        ),
        migrations.AlterField(
            model_name='squad',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.preview'),
        ),
    ]
