# Generated by Django 4.1 on 2022-11-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_game_date_remove_game_guest_remove_game_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(1, 'forward'), (4, 'goalkeeper'), (3, 'defender'), (2, 'midfielder')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'user')], default=2),
        ),
    ]
